
title: Tanim Mahmud
email: tanimmahmud08@gmail.com
description: This is a portfolio site of Tanim Mahmud
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tanimmahmud.github.io" # the base hostname & protocol for your site
github_username:  tanimmahmud

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-sitemap
